
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/res/res.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/jszip/jszip.js",
	"libs/SDK/SDKUtil.js",
	"bin-debug/data/model/ModelBase.js",
	"bin-debug/sdk/ChannelDefine.js",
	"bin-debug/data/model/old/ModelThing.js",
	"bin-debug/view/item/BaseTipsBar.js",
	"bin-debug/sdk/data/ILoginInfo.js",
	"bin-debug/sdk/handler/SDKWanBa.js",
	"bin-debug/data/FishData.js",
	"bin-debug/sdk/sa/SaTalkingData.js",
	"bin-debug/view/base/BaseSystemPanel.js",
	"bin-debug/view/base/BaseTabView.js",
	"bin-debug/view/base/BaseUI.js",
	"bin-debug/view/base/BaseWindowPanel.js",
	"bin-debug/view/body/fish/FishBase.js",
	"bin-debug/view/base/BaseComp.js",
	"bin-debug/sdk/HttpUtil.js",
	"bin-debug/data/manager/old/BagManager.js",
	"bin-debug/data/manager/old/DecorateManager.js",
	"bin-debug/data/manager/old/EnemyManager.js",
	"bin-debug/data/manager/old/FactoryManager.js",
	"bin-debug/data/manager/old/FieldGuideManager.js",
	"bin-debug/data/manager/old/FriendManager.js",
	"bin-debug/data/manager/old/LoginManager.js",
	"bin-debug/data/manager/old/MailManager.js",
	"bin-debug/data/manager/old/OfflineManager.js",
	"bin-debug/data/manager/old/PlayerManager.js",
	"bin-debug/data/manager/old/RandomEventManager.js",
	"bin-debug/data/manager/old/RedPointManager.js",
	"bin-debug/data/manager/old/SmashEggManager.js",
	"bin-debug/data/manager/old/SyncFactory.js",
	"bin-debug/data/manager/old/SyncManager.js",
	"bin-debug/data/manager/old/TaskManager.js",
	"bin-debug/data/manager/old/TechnologyManager.js",
	"bin-debug/data/manager/old/TopRankManager.js",
	"bin-debug/data/manager/old/TurnplateManager.js",
	"bin-debug/data/manager/old/VisiteManager.js",
	"bin-debug/data/manager/PathManager.js",
	"bin-debug/common/GameCommon.js",
	"bin-debug/data/model/ModelMap.js",
	"bin-debug/data/model/ModelMapNode.js",
	"bin-debug/data/model/ModelText.js",
	"bin-debug/data/model/old/ModelAchieve.js",
	"bin-debug/data/model/old/ModelAward.js",
	"bin-debug/data/model/old/ModelBron.js",
	"bin-debug/data/model/old/ModelDailyTask.js",
	"bin-debug/data/model/old/ModelDecorate.js",
	"bin-debug/data/model/old/ModelDecorateLv.js",
	"bin-debug/data/model/old/ModelEffect.js",
	"bin-debug/data/model/old/ModelFieldGuide.js",
	"bin-debug/data/model/old/ModelFish.js",
	"bin-debug/data/model/old/ModelFishLv.js",
	"bin-debug/data/model/old/ModelItem.js",
	"bin-debug/data/model/old/ModelLevel.js",
	"bin-debug/data/model/old/ModelMonthCard.js",
	"bin-debug/data/model/old/ModelRandEvent.js",
	"bin-debug/data/model/old/ModelSevenLogin.js",
	"bin-debug/data/model/old/ModelShop.js",
	"bin-debug/data/model/old/ModelSynthetic.js",
	"bin-debug/data/model/old/ModelTechnology.js",
	"bin-debug/common/GameErrorTip.js",
	"bin-debug/data/model/old/ModelTurnplate.js",
	"bin-debug/data/MonthCard.js",
	"bin-debug/data/Player.js",
	"bin-debug/data/RankData.js",
	"bin-debug/data/SimplePlayer.js",
	"bin-debug/data/vo/Grid.js",
	"bin-debug/define/GameDefine.js",
	"bin-debug/define/GoodsDefine.js",
	"bin-debug/define/UnitDefine.js",
	"bin-debug/event/FishTankEevent.js",
	"bin-debug/event/GameDispatcher.js",
	"bin-debug/event/GameEvent.js",
	"bin-debug/GraphicsUtils.js",
	"bin-debug/interface/IFish.js",
	"bin-debug/interface/IModule.js",
	"bin-debug/interface/IRedPoint.js",
	"bin-debug/load/LoadManager.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/Main.js",
	"bin-debug/net/HttpManager.js",
	"bin-debug/net/message/BuffManager.js",
	"bin-debug/net/message/MESSAGE_ID.js",
	"bin-debug/net/message/Message.js",
	"bin-debug/net/MessageErrorManager.js",
	"bin-debug/net/MessageReceive.js",
	"bin-debug/net/MessageSend.js",
	"bin-debug/net/NetBase.js",
	"bin-debug/net/NetManager.js",
	"bin-debug/common/GameSkin.js",
	"bin-debug/sdk/container/ISDKGiftContainer.js",
	"bin-debug/sdk/container/ISDKPayContainer.js",
	"bin-debug/sdk/container/ISDKShareContainer.js",
	"bin-debug/sdk/container/SDKShareContainer.js",
	"bin-debug/sdk/data/IADInfo.js",
	"bin-debug/common/InfiniteNumber.js",
	"bin-debug/sdk/data/IPayInfo.js",
	"bin-debug/sdk/data/IPlayerInfo.js",
	"bin-debug/sdk/data/ISDKResourceConfig.js",
	"bin-debug/sdk/data/ISDKShareInfo.js",
	"bin-debug/common/RedPoint.js",
	"bin-debug/view/warehouse/WarehousePanel.js",
	"bin-debug/sdk/ISDKHandler.js",
	"bin-debug/sdk/ISDKStatistics.js",
	"bin-debug/data/BeVisitedPlayer.js",
	"bin-debug/sdk/SDKDefine.js",
	"bin-debug/sdk/SDKManager.js",
	"bin-debug/sound/SoundDefine.js",
	"bin-debug/sound/SoundFactory.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/tool/SineBase.js",
	"bin-debug/tool/Tool.js",
	"bin-debug/tool/TweenLiteUtil.js",
	"bin-debug/view/achievement/AchievementPanel.js",
	"bin-debug/view/activity/invitegift/InviteGiftPanel.js",
	"bin-debug/view/activity/limitgift/GiftTimeLimitPanel.js",
	"bin-debug/view/activity/loginseven/LoginSevenPanel.js",
	"bin-debug/view/activity/monthcard/MonthCardPanel.js",
	"bin-debug/view/alert/AlertDisconnect.js",
	"bin-debug/view/alert/AlertHint.js",
	"bin-debug/view/alert/AlertOfflineEarnings.js",
	"bin-debug/view/alert/DescAlertPanel.js",
	"bin-debug/view/alert/UnLockAlertHint.js",
	"bin-debug/view/alert/WarningPanel.js",
	"bin-debug/data/BookData.js",
	"bin-debug/view/base/BasePopPanel.js",
	"bin-debug/data/CrownData.js",
	"bin-debug/_GF.js",
	"bin-debug/data/manager/DataManager.js",
	"bin-debug/data/manager/Language.js",
	"bin-debug/view/base/CurrencyBar.js",
	"bin-debug/view/base/GoodsInstence.js",
	"bin-debug/view/base/SoundBtn.js",
	"bin-debug/view/base/SoundRadioBtn.js",
	"bin-debug/view/base/TabBtnGroup.js",
	"bin-debug/view/base/TabBtnGroup2.js",
	"bin-debug/view/body/Animation.js",
	"bin-debug/view/body/Bubble.js",
	"bin-debug/view/body/DropIcon.js",
	"bin-debug/view/body/fish/CdLock.js",
	"bin-debug/view/body/fish/EnjoyFish.js",
	"bin-debug/view/body/fish/Fish.js",
	"bin-debug/data/manager/ModelManager.js",
	"bin-debug/view/body/fish/RandEevent.js",
	"bin-debug/view/body/FlutterHint.js",
	"bin-debug/view/body/LevelUpHint.js",
	"bin-debug/view/body/SecOutputAddAnim.js",
	"bin-debug/view/dailytask/DailyTaskPanel.js",
	"bin-debug/view/decorate/DecorateGashaponPanel.js",
	"bin-debug/view/decorate/DecoratePanel.js",
	"bin-debug/view/enemy/EnemyListPaneL.js",
	"bin-debug/view/fieldguide/CrownBar.js",
	"bin-debug/view/fieldguide/FieldGuidePanel.js",
	"bin-debug/view/FishTankLayer.js",
	"bin-debug/view/FishTankView.js",
	"bin-debug/view/friend/FriendApplyListPanel.js",
	"bin-debug/view/friend/FriendGiftListPanel.js",
	"bin-debug/view/friend/FriendGiftPanel.js",
	"bin-debug/view/friend/FriendPanel.js",
	"bin-debug/view/friend/FriendSeachPanel.js",
	"bin-debug/view/heaven/HeavenPanel.js",
	"bin-debug/data/manager/old/AchieveManager.js",
	"bin-debug/view/item/FieldGuideTipsBar.js",
	"bin-debug/view/item/ItemIntroducebar.js",
	"bin-debug/view/item/ShopTipsBar.js",
	"bin-debug/view/login/CreateRoleView.js",
	"bin-debug/view/login/LoginView.js",
	"bin-debug/view/lottery/TurnplatePanel.js",
	"bin-debug/view/lottery/TurnplaterResultAlert.js",
	"bin-debug/view/mail/MailContentPanel.js",
	"bin-debug/view/mail/MailListPanel.js",
	"bin-debug/view/main/BottonMenuLayer.js",
	"bin-debug/view/main/MainPanelLayer.js",
	"bin-debug/view/main/PlayerHeadBar.js",
	"bin-debug/view/MainView.js",
	"bin-debug/view/other/OtherFeedView.js",
	"bin-debug/view/other/OtherFishTank.js",
	"bin-debug/view/pay/ShopPayPanel.js",
	"bin-debug/view/prompt/NoviceGuidePanel.js",
	"bin-debug/view/prompt/PromptInfo.js",
	"bin-debug/view/prompt/PromptPanel.js",
	"bin-debug/view/scene/MainScene.js",
	"bin-debug/view/scene/MapInfo.js",
	"bin-debug/view/scene/MapLayer.js",
	"bin-debug/view/scene/ModuleLayer.js",
	"bin-debug/view/shop/BatchDisposebar.js",
	"bin-debug/view/shop/ShopGoldPanel.js",
	"bin-debug/view/shop/ShopPanel.js",
	"bin-debug/view/smashEgg/SmashEggLotteryPanel.js",
	"bin-debug/view/smashEgg/SmashEggUserListPanel.js",
	"bin-debug/view/system/SystemSetPanel.js",
	"bin-debug/view/technology/TechnologyPanel.js",
	"bin-debug/view/toprank/TopRankPanel.js",
	"bin-debug/view/upgrade/FishTankAdvancePanel.js",
	"bin-debug/view/upgrade/MainUpgradeItem.js",
	"bin-debug/view/upgrade/UpgradePanel.js",
	"bin-debug/view/warehouse/BagPanel.js",
	"bin-debug/view/warehouse/CrownSynthesisPanel.js",
	"bin-debug/view/warehouse/GemSynthesisPanel.js",
	"bin-debug/AssetAdapter.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "exactFit",
		contentWidth: 600,
		contentHeight: 1067,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};