/**
 * 消息号
 * @author
 *
 */
var MESSAGE_ID;
(function (MESSAGE_ID) {
    MESSAGE_ID[MESSAGE_ID["GAME_LOGON_MESSAGE"] = 100] = "GAME_LOGON_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["ERROR_TIP_MESSAGE"] = 110] = "ERROR_TIP_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["GAME_TICK_MESSAGE"] = 99] = "GAME_TICK_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["LOGIN_SERVER_MESSAGE"] = 103] = "LOGIN_SERVER_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["CREATE_ROLE_MESSAGE"] = 104] = "CREATE_ROLE_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["ENTER_GAME_MESSAGE"] = 105] = "ENTER_GAME_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PLAYER_MESSAGE"] = 106] = "PLAYER_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["GAME_SYNC_MESSAGE"] = 107] = "GAME_SYNC_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["GAME_TOKEN_MESSAGE"] = 109] = "GAME_TOKEN_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["TIMEOUT_MESSAGE"] = 111] = "TIMEOUT_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["REPEAT_LOGIN_MESSAGE"] = 112] = "REPEAT_LOGIN_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PALYER_HAPPINESS_MSG"] = 160] = "PALYER_HAPPINESS_MSG";
    MESSAGE_ID[MESSAGE_ID["PALYER_DAILY_RECORD"] = 161] = "PALYER_DAILY_RECORD";
    MESSAGE_ID[MESSAGE_ID["PALYER_BUFF_RECORD"] = 162] = "PALYER_BUFF_RECORD";
    /**----好友----**/
    MESSAGE_ID[MESSAGE_ID["FRIEND_LISTINIT_MSG"] = 201] = "FRIEND_LISTINIT_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_SEACH_MSG"] = 202] = "FRIEND_SEACH_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_ADD_MSG"] = 203] = "FRIEND_ADD_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_DELETE_MSG"] = 204] = "FRIEND_DELETE_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_AGREE_APPLY_MSG"] = 205] = "FRIEND_AGREE_APPLY_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_REJECT_APPLY_MSG"] = 206] = "FRIEND_REJECT_APPLY_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_GIFT_MESAAGE"] = 207] = "FRIEND_GIFT_MESAAGE";
    MESSAGE_ID[MESSAGE_ID["FRIEND_APPLYUPDATYE_MSG"] = 208] = "FRIEND_APPLYUPDATYE_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_GIVEFOOD_MSG"] = 209] = "FRIEND_GIVEFOOD_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_ADD_SUCCESS_MSG"] = 210] = "FRIEND_ADD_SUCCESS_MSG";
    MESSAGE_ID[MESSAGE_ID["ENEMY_LIST_MSG"] = 211] = "ENEMY_LIST_MSG";
    MESSAGE_ID[MESSAGE_ID["FRIEND_BE_VIEWED_MSG"] = 220] = "FRIEND_BE_VIEWED_MSG";
    MESSAGE_ID[MESSAGE_ID["PLAYER_TO_DO_SOMEBODY"] = 221] = "PLAYER_TO_DO_SOMEBODY";
    /**赚钻石**/
    MESSAGE_ID[MESSAGE_ID["INIVTEGIFT_FRIENDLIST_MSG"] = 222] = "INIVTEGIFT_FRIENDLIST_MSG";
    MESSAGE_ID[MESSAGE_ID["INIVTEGIFT_REWARD_MSG"] = 223] = "INIVTEGIFT_REWARD_MSG";
    /**砸蛋**/
    MESSAGE_ID[MESSAGE_ID["SMASHEGG_FRIEND_INFO_MSG"] = 230] = "SMASHEGG_FRIEND_INFO_MSG";
    MESSAGE_ID[MESSAGE_ID["SMASHEGG_BE_VIEWD_MSG"] = 231] = "SMASHEGG_BE_VIEWD_MSG";
    MESSAGE_ID[MESSAGE_ID["SMASHEGG_BE_REWARD_MSG"] = 232] = "SMASHEGG_BE_REWARD_MSG";
    MESSAGE_ID[MESSAGE_ID["HEAVEN_REWARD_MSG"] = 302] = "HEAVEN_REWARD_MSG";
    /**装饰、神器**/
    MESSAGE_ID[MESSAGE_ID["DECORATE_SHOW_MESSAGE"] = 351] = "DECORATE_SHOW_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["DECORATE_GASHAPON_MESSAGE"] = 352] = "DECORATE_GASHAPON_MESSAGE";
    /**排行榜 */
    MESSAGE_ID[MESSAGE_ID["TOPRANK_LIST_MESSAGE"] = 360] = "TOPRANK_LIST_MESSAGE";
    /**月卡、终生卡 */
    MESSAGE_ID[MESSAGE_ID["MONTHLY_CARD_REWARD_MESSAGE"] = 370] = "MONTHLY_CARD_REWARD_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["SHOP_BUY_GOLD_MESSAGE"] = 371] = "SHOP_BUY_GOLD_MESSAGE";
    /**科技**/
    MESSAGE_ID[MESSAGE_ID["TECHNOLOGY_INIT_MSG"] = 401] = "TECHNOLOGY_INIT_MSG";
    MESSAGE_ID[MESSAGE_ID["TECHNOLOGY_UPGRADE_MSG"] = 402] = "TECHNOLOGY_UPGRADE_MSG";
    /**转盘**/
    MESSAGE_ID[MESSAGE_ID["TURNPLATE_LOTTERY_MSG"] = 501] = "TURNPLATE_LOTTERY_MSG";
    /**离线收益**/
    MESSAGE_ID[MESSAGE_ID["PLAYER_OFFLINE_EARNINGS"] = 601] = "PLAYER_OFFLINE_EARNINGS";
    /**鱼食恢复**/
    MESSAGE_ID[MESSAGE_ID["FISH_FOOD_RECIVE_MSG"] = 701] = "FISH_FOOD_RECIVE_MSG";
    /**日常任务**/
    MESSAGE_ID[MESSAGE_ID["DAILY_TASK_UPDATE_MSG"] = 801] = "DAILY_TASK_UPDATE_MSG";
    MESSAGE_ID[MESSAGE_ID["DAILY_TASK_REWARD_MSG"] = 802] = "DAILY_TASK_REWARD_MSG";
    /**成就**/
    MESSAGE_ID[MESSAGE_ID["ACHIEVEMENT_INIT_MSG"] = 901] = "ACHIEVEMENT_INIT_MSG";
    MESSAGE_ID[MESSAGE_ID["ACHIEVEMENT_UPDATE_MSG"] = 902] = "ACHIEVEMENT_UPDATE_MSG";
    MESSAGE_ID[MESSAGE_ID["ACHIEVEMENT_REWARD_MSG"] = 903] = "ACHIEVEMENT_REWARD_MSG";
    /**成就**/
    MESSAGE_ID[MESSAGE_ID["SHARE_REWARD_MESSAGE"] = 1001] = "SHARE_REWARD_MESSAGE";
    /**邮件**/
    MESSAGE_ID[MESSAGE_ID["PLAYER_MAIL_MESSAGE"] = 190] = "PLAYER_MAIL_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PLAYER_MAIL_READ_MESSAGE"] = 191] = "PLAYER_MAIL_READ_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PLAYER_MAIL_GET_ACCESSORY_MESSAGE"] = 192] = "PLAYER_MAIL_GET_ACCESSORY_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PLAYER_MAIL_DELETE_MESSAGE"] = 193] = "PLAYER_MAIL_DELETE_MESSAGE";
    MESSAGE_ID[MESSAGE_ID["PLAYER_UPDATA_CURRENCY"] = 163] = "PLAYER_UPDATA_CURRENCY";
})(MESSAGE_ID || (MESSAGE_ID = {}));
//# sourceMappingURL=MESSAGE_ID.js.map