// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package p.my.rpc.proto.model;

public final class RPCServerState {
  private RPCServerState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p_my_rpc_proto_ServerStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p_my_rpc_proto_ServerStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p_my_rpc_proto_ServerStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p_my_rpc_proto_ServerStateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\016p.my.rpc.proto\"Z\n\022Server" +
      "StateRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014" +
      "\n\004host\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\022\016\n\006online\030\005 \001" +
      "(\005\"$\n\023ServerStateResponse\022\r\n\005state\030\001 \001(\010" +
      "B(\n\024p.my.rpc.proto.modelB\016RPCServerState" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_p_my_rpc_proto_ServerStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p_my_rpc_proto_ServerStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p_my_rpc_proto_ServerStateRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Host", "Port", "Online", });
    internal_static_p_my_rpc_proto_ServerStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_p_my_rpc_proto_ServerStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p_my_rpc_proto_ServerStateResponse_descriptor,
        new java.lang.String[] { "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
