// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package p.my.rpc.proto.model;

public interface ServerStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.my.rpc.proto.ServerStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool state = 1;</code>
   */
  boolean getState();
}
