// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package p.my.rpc.proto.model;

public interface ServerStateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.my.rpc.proto.ServerStateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string host = 3;</code>
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 3;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>optional int32 port = 4;</code>
   */
  int getPort();

  /**
   * <code>optional int32 online = 5;</code>
   */
  int getOnline();
}
