// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_service.proto

package p.my.rpc.proto.service;

public final class RPCServerStateService {
  private RPCServerStateService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024server_service.proto\022\016p.my.rpc.proto\032\014" +
      "server.proto2j\n\022ServerStateService\022T\n\tse" +
      "ndState\022\".p.my.rpc.proto.ServerStateRequ" +
      "est\032#.p.my.rpc.proto.ServerStateResponse" +
      "B1\n\026p.my.rpc.proto.serviceB\025RPCServerSta" +
      "teServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          p.my.rpc.proto.model.RPCServerState.getDescriptor(),
        }, assigner);
    p.my.rpc.proto.model.RPCServerState.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
