// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package com.wycx.rpc.proto.service;

public final class GreetingService {
  private GreetingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023hello_service.proto\022\022com.wycx.rpc.prot" +
      "o\032\013hello.proto2_\n\014HelloService\022O\n\010sayHel" +
      "lo\022 .com.wycx.rpc.proto.HelloRequest\032!.c" +
      "om.wycx.rpc.proto.HelloResponseB/\n\032com.w" +
      "ycx.rpc.proto.serviceB\017GreetingServiceP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wycx.rpc.proto.model.Hello.getDescriptor(),
        }, assigner);
    com.wycx.rpc.proto.model.Hello.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
